services:
  web:
    build:
      context: .
      args:
        UID: 1000
        GID: 1000
    ports:
      - "5015:5015"
    volumes:
      - ./static:/app/static  # Monta la cartella static locale nel container
    environment:
      - FLASK_DEBUG=False
    labels:
      - traefik.enable=true
      - traefik.http.routers.rtr-player.rule=Host(`player.stefanoteodorani.it`)
      - traefik.http.routers.rtr-player.tls=true
      - traefik.http.routers.rtr-player.tls.certresolver=le
      - traefik.http.services.svc-player.loadbalancer.server.port=5015
      - traefik.http.routers.rtr-player.middlewares=my-geoblock@file
      - traefik.docker.network=traefik-proxy

    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    external: true
